spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/15803830205/config-server
          username: 5758778222@qq.com
          password: panyang126
  rabbitmq:
    username: guest
    password: guest
    connection-timeout: 15000
    port: 5672
    host: 192.168.92.133
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/